Resources:
  S3Data:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pengantar-sagemaker
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t2.medium
      RoleArn: arn:aws:iam::623127157773:role/sagemaker-role